Create boom.json
open-objecten/objecttypes pull request #1
Opened 2021-06-03 18:28 UTC by dariomory

First draft of the updated imvertorlite tested on the "Boom" class.

```
python imvertorlite.py -f ggm.xml -n Boom
```

2021-06-17 04:34 UTC, joeribekker requested changes

2021-06-17 04:34 UTC, joeribekker commented on community-standards/boom.json
> +      "stereotype": "enum",
These can all be gone.

2021-06-17 04:34 UTC, joeribekker commented on community-standards/boom.json
> +      ],
Can be gone.

2021-06-17 04:34 UTC, joeribekker commented on community-standards/boom.json
> +  "status": "Proposed",
These can also be gone.

2021-06-18 07:22 UTC, joeribekker requested changes
We should sort enums to prevent changes everytime we generete and example has an incorrect format

2021-06-22 13:56 UTC, joeribekker commented
> Is het een idee om ook richtlijnen voor veldnaamgeving te ontwikkelen? Voor Amsterdam hebben we deze (kleine) set van [richtlijnen](https://github.com/Amsterdam/amsterdam-schema/wiki/Modellering-Best-Practices) die waarschijnlijk deels ook in de NL API REST Design Rules [terecht gaan komen](https://github.com/Geonovum/KP-APIs/pull/373).

Goed punt! Helaas zie ik alweer discussie in die Github repo en verschillen tussen DSO en NL API strategie (wat een fork is van DSO...). Enige verschil is volgens mij dat we beginnen met een kleine letter? Ik zie verder niet direct conflicten, heb jij deze wel gezien?

> Verder vroeg ik me ook af wat de meerwaarde van het $id veld op property niveau is? Is dat omdat het automatisch gegenereerd wordt of zijn er clients die dat ergens voor nodig hebben?

Weinig meerwaarde in deze context maar het kan ook geen kwaad. Je zou het kunnen gebruiken voor als je wilt verwijzen naar hetzelfde veld binnen een andere scope (een object-property bijv.).

2021-06-22 13:57 UTC, joeribekker commented
@dariomory Can you convert the first letter of each property/id (not title) to a lowercase version?

2021-06-22 13:58 UTC, joeribekker requested changes
Can you convert the first letter of each property/id (not title) to a lowercase version?

2021-06-22 15:46 UTC, mtrimpe commented
> Enige verschil is volgens mij dat we beginnen met een kleine letter?

Ja; het gaat hier alleen om de lowercase eerste letter inderdaad.

De andere punten zijn concrete anti-patterns die we zijn tegengekomen in bij ons aangeleverde schemas. Alle 'requested changes' voor schema's proberen we daarin vast te leggen als richtlijn voor toekomstige contributors.

2021-06-23 09:06 UTC, dariomory commented
> Can you convert the first letter of each property/id (not title) to a lowercase version?

Fixed in 66b8f6d3602b163d6a98ad6c1d4a37f0e64338e5

2021-06-24 07:19 UTC, joeribekker commented
> > Enige verschil is volgens mij dat we beginnen met een kleine letter?
> 
> Ja; het gaat hier alleen om de lowercase eerste letter inderdaad.
> 
> De andere punten zijn concrete anti-patterns die we zijn tegengekomen in bij ons aangeleverde schemas. Alle 'requested changes' voor schema's proberen we daarin vast te leggen als richtlijn voor toekomstige contributors.

Mooi, ik denk dat ik dan gewoon verwijs naar jullie of NL API strategie (hoewel ik deze laatste te weinig praktijk en te veel theorie vind hanteren). Lijkt me niet zinvol om steeds hetzelfde lijstje te gaan bijhouden.

2021-06-24 09:05 UTC, joeribekker commented
Closing in favor of #2 with README, credits and final JSON-schema.

2021-06-24 09:06 UTC, closed without merging