5 nieuwe objecten toegevoegd die in KISS gebruikt worden
open-objecten/objecttypes pull request #10
Opened 2023-10-10 17:23 UTC by RutgerICATT

Ik heb 5 JSON-schema's toegevoegd die in KISS gebruikt worden, Medewerker, Afdelingen en groepen, VAC en PDC. 

Met vriendelijke groet, 

Rutger Boekhorst
ICATT

2023-10-12 08:57 UTC, joeribekker requested changes
2 inhoudelijke punten, zie comments.

Verder dan over de aanlevering:

1. Geen spaties graag (vervang eventueel met streepjes of underscores) en lowercase JSON-bestandsnamen.
2. README graag in markdown formaat, bestandsnaam moet zijn `README.md`

Voorbeeld staat hier: https://github.com/open-objecten/objecttypes/blob/main/community-concepts/productaanvraag/README-denhaag.md

De zin onder de titel in het voorbeeld, kan de tekst bevatten die nu in je READMEs staan.

Ik zal de documentatie voor aanlevering verbeteren!

2023-10-12 08:57 UTC, joeribekker commented on community-concepts/PDC - kennisartikel/schema kennisartikel SDG v5.json
> +		"type": "object",
Hier begint het JSON schema pas. De attributen erboven zijn onjuist.

2023-10-12 08:57 UTC, joeribekker commented on community-concepts/VAC/VAC-schema.json
> +        "type": "object",
Hier begint het JSON schema pas. Attributen erboven moeten weg.

2023-10-12 19:42 UTC, RutgerICATT commented
Dank voor de review. Ik heb de feedback verwerkt. Ik heb de regel -"type": "object",- wel in de schema's laten zitten ik zag deze bij een andere er ook in staan dus wist niet of deze wel of niet noodzakelijk is. Als deze er nog wel uit moet hoor ik het graag.

Groet, Rutger

2023-10-26 12:57 UTC, RutgerICATT commented
@joeribekker: Er is nog een nieuw objecttype toegevoegd die ik in eerste instantie vergeten was. Zou je deze kunnen controleren en alles doorzetten

2023-10-31 10:35 UTC, joeribekker approved these changes
Ziet er goed uit, toegevoegd.

2023-10-31 10:35 UTC, merged