#24 - Voeg rolOmschrijvingGeneriek weer toe in productaanvraag-dimpac…
open-objecten/objecttypes pull request #25
Opened 2024-08-13 09:12 UTC by andyverberne

…t.json specificatie

2024-08-20 12:12 UTC, edgarvonk requested changes

2024-08-20 12:12 UTC, edgarvonk commented on community-concepts/productaanvraag/productaanvraag-dimpact.json
> -          "roltypeOmschrijving" : "initiator",
Dit nieuwe  `roltypeOmschrijving ` moet niet verwijderd worden toch @andyverberne ? Die hebben wij in ZAC juist nodig voor: https://dimpact.atlassian.net/browse/PZ-3471 Ik dacht dat het idee was dat we beide velden in de spec wilden hebben?

2024-08-29 12:32 UTC, edgarvonk approved these changes

2024-08-29 12:32 UTC, edgarvonk commented on community-concepts/productaanvraag/productaanvraag-dimpact.json
> -          "roltypeOmschrijving" : "initiator",
Aja, dit gaat om de voorbeelden. Prima zo :-)

2024-09-17 13:22 UTC, joeribekker approved these changes

2024-09-17 13:22 UTC, merged